### ISSUE TITLE
`cycle-tags ... --occupied` has odd behavior with multiple outputs

### ISSUE THREAD

**Issue by justinlovinger** [stefur/flow#3]
I cannot figure out the exact pattern, but things are definitely wonky with multiple outputs. For example, with `1`, `2`, `7` and `8` occupied on one output and `1` occupied on another output, if I run `flow cycle-tags previous 32 --occupied` with `7` selected, it will sometimes cycle to `6` then `5`, but if I cycle back to `7` `flow cycle-tags previous 32 --occupied` may then cycle correctly to `2`.

I have not noticed similar behavior with only one output.

**Comment by stefur** [comment]
My bad, I forgot that the handling of the event for view tags must only capture tags of focused output for the cycling to function properly. Would you mind trying #4 just to make sure I catched it?

Thanks for reporting!
